In [1]:
import itertools
import numpy as np

from scipy.sparse import csr_matrix

from utilities import chol_params_to_lower_triangular_matrix
from utilities import cov_matrix_to_sdcorr_params
from utilities import number_of_triangular_elements_to_dimension
from utilities import dimension_to_number_of_triangular_elements

from utilities import commutation_matrix
from utilities import elimination_matrix
from utilities import duplication_matrix
from utilities import transformation_matrix

from jax import jacfwd
from kernel_transformations_jax import covariance_from_internal as covariance_from_internal_jax
from kernel_transformations_jax import sdcorr_from_internal as sdcorr_from_internal_jax
from kernel_transformations_jax import probability_from_internal as probability_from_internal_jax

from numpy.testing import assert_array_almost_equal

$$
\tilde{\text{vec}}
\left (
\begin{matrix}
(0,0)  &        &        &        \\
(1, 0) & (1,1)  &        &        \\
(2, 0) & (2, 1) & (2, 2) &        \\
(3, 0) & (3, 1) & (3, 2) & (3, 3) \\
\end{matrix}
\right ) =:
\tilde{\text{vec}}(L) = 
\big ( (0,0), (1,0), (1,1), (2,0), (2, 1), (2, 2), (3, 0), (3, 1), (3, 2), (3, 3) \big )^\top := v
$$

The following two functions allow us to move between these two representation of a (lower-triangular) matrix in a bijective fashion.

In [2]:
MAX_VALUE = 500

SEQUENCE_I = list(itertools.chain.from_iterable(itertools.repeat(i-1, i) for i in range(1, MAX_VALUE)))
SEQUENCE_J = list(itertools.chain.from_iterable(range(i-1) for i in range(1, MAX_VALUE)))

def _vectorized_index_to_matrix_index(index):
    return SEQUENCE_I[index], SEQUENCE_J[index]

def _matrix_index_to_vectorized_index(i, j):
    return int(i * (i + 1) / 2) +  j

for k in range(100):
    assert _matrix_index_to_vectorized_index(*_vectorized_index_to_matrix_index(k)) == k

In [3]:
def seq(n_list, max_n=10):
    n = len(n_list)
    if n < max_n:
        n_list.append(n_list[-1] + n + 1)
        n_list = seq(n_list, max_n)
        
    return n_list


TO_DROP_SEQUENCE = seq([0], max_n=500)
SEQUENCE_SDCORR = [e for e in range(125250) if e not in TO_DROP_SEQUENCE]

## Derivative of ``covariance_from_internal``

The graph we want to differentiate looks as follow

$$\tilde{\text{vec}}(L) \to L \to L L^\top =: \Sigma \to \tilde{\text{vec}}(\Sigma) \,,$$
where $L$ is the Cholesky factor of the covariance matrix $\Sigma$.
Let us define a function $f: \mathbb{R}^m \to \mathbb{R}^m, x \mapsto f(x)$, which takes an internal vector $x$ (of correct dimension) and transforms it to the covariance matrix as depicted above.
We want to find the Jacobian of $f$, i.e.
$$
J(f) = \left ( \frac{\partial \, f_i}{\partial \, x_j} \right )_{i, j = 1, \dots, m}
$$

We tackle this problem by finding an explicit expression for ${\partial f_i}/{\partial x_j}$ and then looping over $i,j = 1,\dots, m$.

Henceforth let $i, j$ be given and let $\Sigma = (\sigma_{i, j})$.
Note that for each $j$ we can find a unique index tuple $(a, b) = (a(j), b(j))$ such that $\tilde{\text{vec}}(L)_j = L_{a, b}$ and equivalently we find $(n, m) = (n(i), m(i))$ such that $\tilde{\text{vec}}(\Sigma)_i = \sigma_{n, m}$. Also note that for these indices it always holds that $a \geq b$ and $n \geq m$.

Now note again that with $L = \left [ \begin{matrix} \ell_1 \\ \vdots \\ \ell_m \end{matrix} \right ]$, we have $\sigma_{k, l} = \ell_k^ \, \bullet \ell_l$.
Hence we get

$$
\frac{\partial \, f_i}{\partial \, x_j} = 
\frac{\partial}{\partial L_{a, b}} \left ( \ell_n \bullet \, \ell_m \right ) = 
\frac{\partial}{\partial L_{a, b}} \left ( \sum_{k=1}^{m} L_{n, k} L_{m, k} \right ) = 
\mathbb{1}(b \leq m) \left [ \mathbb{1}(a = n) L_{m, b} + \mathbb{1}(a = m) L_{n, b} \right ]
$$

In [64]:
def derivative_covariance_from_internal(internal_values):
    chol = chol_params_to_lower_triangular_matrix(internal_values)
    
    dim = len(chol)
    
    K = commutation_matrix(dim)
    
    d0_a = np.eye(dim ** 2) + K
    d0_b = np.kron(chol, np.eye(dim))
    d0 = d0_a @ d0_b
    
    L = elimination_matrix(dim)
    D = duplication_matrix(dim)
    
    d1 = L @ d0 @ L.T
    
    return d1

## Example / Testing

In [65]:
J = jacfwd(covariance_from_internal_jax)

In [66]:
def get_random_internal(dim, seed=0):
    np.random.seed(seed)
    chol = np.tril(np.random.randn(dim, dim))
    internal = chol[np.tril_indices(len(chol))]
    return internal

In [67]:
for dim in range(10, 50):
    internal = get_random_internal(dim)

    jax_deriv = J(internal)

    my_deriv = derivative_covariance_from_internal(internal)

    assert_array_almost_equal(jax_deriv, my_deriv)

## Timeit

In [16]:
internal = get_random_internal(20)

In [17]:
%timeit J(internal)

13.4 ms ± 187 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [18]:
%timeit derivative_covariance_from_internal(internal)

15.7 ms ± 332 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# Derivative of ``sdcorr_from_internal``

The graph we want to differentiate looks as follow

$$\tilde{\text{vec}}(L) \to L \to L L^\top =: \Sigma \to \mathcal{P} \to \bar{\text{vec}}(\mathcal{P}) \,,$$
where $L$ is the Cholesky factor of the covariance matrix $\Sigma$ and $\mathcal{P}$ denotes the *modified* correlation matrix. With modified correlation matrix we mean a correlation matrix that has the standard deviations written on the diagonal instead of ones. Moreover, the new operate $\bar{\text{vec}}$ maps the diagonal elements of a matrix to the first entries of the resulting vector and proceeds to fill the remaining entries using the operator $\tilde{\text{vec}}$. That is, if we let $M$ be some lower-triangular, $m \times m$ matrix and define $M'$ as the $(m-1) \times (m-1)$ lower-triangular matrix containing the lower-triangular elements of $M$ except for the diagonal elements, then

$$ \bar{\text{vec}}(M) = \left ( \text{diag}(M), \tilde{\text{vec}}(M') \right )$$

In [85]:
np.arange(9).reshape(3, 3).ravel

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.ha

In [3]:
def derivative_sdcorr_from_internal(internal_values):
    
    X = chol_params_to_lower_triangular_matrix(internal_values)
    dim = len(X)
    
    I = np.eye(dim)
    S = X @ X.T
    A = np.multiply(I, X)
    #A = np.diag(np.diag(X))
    V = np.linalg.inv(A)
    P = V @ S @ V + A - I
    
    K = commutation_matrix(dim)
    Y = np.diag(I.ravel('F'))
    
    N = np.kron(I, X) @ K + np.kron(X, I)
    
    VS = V @ S
    B = np.kron(V, V)
    H = np.kron(VS, I)
    J = np.kron(I, VS)
    
    dpdx = Y + B @ N - (H + J) @ B @ Y
    
    T = transformation_matrix(dim)
    D = duplication_matrix(dim)
    
    return T @ dpdx @ D

In [2]:
duplication_matrix(3)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1]])

In [9]:
duplication_matrix(3) @ elimination_matrix(3)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1]])

## Example / Testing

In [4]:
J = jacfwd(sdcorr_from_internal_jax)

In [5]:
internal = np.array([1., 2, 4, 6, 1, 0.5])

In [7]:
J(internal).round(2)

DeviceArray([[ 1.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
             [ 0.  ,  0.45,  0.89,  0.  ,  0.  ,  0.  ],
             [ 0.  ,  0.  ,  0.  ,  0.98,  0.16,  0.08],
             [ 0.  ,  0.18, -0.09,  0.  ,  0.  ,  0.  ],
             [ 0.  ,  0.  ,  0.  ,  0.01, -0.03, -0.01],
             [ 0.  ,  0.16, -0.08, -0.02,  0.13, -0.01]], dtype=float32)

In [8]:
derivative_sdcorr_from_internal(internal).round(2)

array([[ 1.00e+00,  0.00e+00,  0.00e+00,  0.00e+00,  0.00e+00,  0.00e+00],
       [ 0.00e+00,  2.50e-01,  8.80e-01,  0.00e+00,  0.00e+00,  0.00e+00],
       [ 0.00e+00,  0.00e+00,  0.00e+00,  4.80e+01,  8.00e+00, -5.91e+02],
       [ 0.00e+00,  2.50e-01, -1.20e-01,  0.00e+00,  0.00e+00,  0.00e+00],
       [ 0.00e+00,  0.00e+00,  0.00e+00,  2.00e+00,  0.00e+00, -2.40e+01],
       [ 0.00e+00,  3.00e+00, -1.50e+00,  1.00e+00,  2.00e+00, -1.60e+01]])

In [102]:
for dim in range(10, 50):
    internal = get_random_internal(dim)
    jax_deriv = J(internal)
    my_deriv = derivative_sdcorr_from_internal(internal)
    assert_array_almost_equal(jax_deriv, my_deriv)
    bad.append(dim)

## Timeit

In [103]:
internal = get_random_internal(20)

In [104]:
%timeit J(internal)

23.5 ms ± 162 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [105]:
%timeit derivative_sdcorr_from_internal(internal)

1.37 s ± 28.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Derivative of ``probability_from_internal``

Let $f: \mathbb{R}^m \to \mathbb{R}^m, x \mapsto \frac{1}{x^\top 1} x$, with $1$ denoting a vector of all ones. Define $\sigma := x^\top 1 = \sum_k x_k$. Then,
$$
J(f)(x) = \frac{1}{\sigma} I_m - \frac{1}{\sigma^2} 1 x^\top \,,
$$
where $I_m$ denotes the $m \times m$ identity matrix.

In [36]:
def derivative_probability_from_internal(internal_values):
    dim = len(internal_values)
    
    sigma = np.sum(internal_values)
    
    left = np.eye(dim)
    
    right = np.ones((dim, dim)) * (internal_values / sigma)
    
    deriv = left - right.T
    deriv /= sigma
    return deriv

## Example / Testing

In [37]:
J = jacfwd(probability_from_internal_jax)

In [50]:
bad = []
for dim in range(5, 50):
    try:
        internal = get_random_internal(dim)
        jax_deriv = J(internal)
        my_deriv = derivative_probability_from_internal(internal)
        assert_array_almost_equal(jax_deriv, my_deriv, decimal=5)
    except AssertionError:
        bad.append(dim)
        
print(bad)

[16, 17]


## Timeit

In [22]:
internal = get_random_internal(20)

In [23]:
%timeit J(internal)

3.78 ms ± 42 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [24]:
%timeit derivative_probability_from_internal(internal)

741 µs ± 14.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
